name: fc3-docker

services:
  app:
    container_name: nodeapp
    image: mestremurai/nodeapp
    build: ./node
    env_file:
      - path: ./node/app/.env
    entrypoint: sh -c "npm install && node index.js"
    tty: true
    volumes:
      - ./node/app:/usr/src/app
    networks:
      - desafionet
    depends_on:
      bd:
        condition: service_healthy

  bd:
    container_name: mysqlbd
    image: mysql:8.3.0
    env_file:
      - path: ./node/app/.env
    volumes:
      - bdfc3:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    tty: true
    networks: 
      - desafionet

  proxy:
    container_name: nginx
    image: mestremurai/nginx
    build: ./nginx
    entrypoint: wait-for app:3000 -t 30 -- /docker-entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks:
      - desafionet
    depends_on:
      - app

networks: 
  desafionet:
    driver: bridge

volumes:
  bdfc3: