FROM nginx:1.24.0

ENV WAIT_FOR_VERSION d48601a8a90c3d22fade68d09b4240739fb44a46

RUN apt-get update &&\
    apt-get -y install netcat wget &&\
    apt-get clean cache

RUN wget -qO /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for &&\
    chmod +x /usr/bin/wait-for

COPY nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT [ "/docker-entrypoint.sh" ]

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]